# Generated by Django 2.1.7 on 2019-06-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
