# Generated by Django 2.1.7 on 2019-08-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190613_2248'),
        ('training', '0002_auto_20190613_2246'),
    ]

    operations = [
    ]
