# Generated by Django 2.1.7 on 2019-08-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_merge_20190814_1415'),
        ('training', '0003_merge_20190816_0449'),
    ]

    operations = [
    ]
