# Generated by Django 2.1.7 on 2019-06-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('machine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=100)),
                ('firmware', models.CharField(default='1.1.1', max_length=100)),
                ('network', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('isremoved', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('user_role', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('breed', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('image_url', models.TextField(default='https://s3.us-east-2.amazonaws.com/brilliantpet.images/1_1560325598428.9006.png')),
                ('weight', models.IntegerField()),
                ('weight_unit', models.CharField(max_length=45)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('link', models.CharField(max_length=145)),
                ('type', models.CharField(max_length=45)),
                ('is_active', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.TextField(default='https://s3.us-east-2.amazonaws.com/brilliantpet.images/1_1560301349979.0452.jpeg')),
                ('notification_token', models.CharField(blank=True, max_length=145)),
                ('rolls_count_at_home', models.IntegerField()),
                ('password', models.CharField(max_length=512)),
                ('login_token', models.CharField(blank=True, max_length=256, null=True)),
                ('isDeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
    ]
