# Generated by Django 2.1.7 on 2019-06-10 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('machine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware', models.CharField(blank=True, max_length=100, null=True)),
                ('network', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('isremoved', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user_role', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('notification_token', models.CharField(blank=True, max_length=145, null=True)),
                ('rolls_count_at_home', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
    ]
