# Generated by Django 2.1.7 on 2019-06-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('breed', models.CharField(max_length=45)),
                ('birthday', models.DateField()),
                ('image_url', models.TextField()),
                ('weight', models.IntegerField()),
                ('weight_unit', models.CharField(max_length=45)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
