# Generated by Django 2.1.7 on 2019-08-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notificationToken',
            field=models.CharField(default='toBeFilled', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='shopify_access_token',
            field=models.CharField(default='shouldBeFilled', max_length=256),
        ),
    ]
