# Generated by Django 2.1.7 on 2019-07-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eventit', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MachineDetails')),
            ],
        ),
        migrations.CreateModel(
            name='notification_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('dev_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_token',
        ),
        migrations.AddField(
            model_name='notification_token',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='events',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]

