# Generated by Django 2.1.7 on 2019-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
