# Generated by Django 2.1.7 on 2019-08-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190816_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notificationToken',
            field=models.CharField(default='toBeFilled', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopify_access_token',
            field=models.CharField(default='shouldBeFilled', max_length=256),
        ),
    ]
