# Generated by Django 2.1.7 on 2019-11-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isflagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
