# Generated by Django 2.1.7 on 2019-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191106_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedetails',
            name='machine_size',
            field=models.CharField(default='standard', max_length=25),
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='roll_length',
            field=models.CharField(default='standard', max_length=25),
        ),
    ]
