# Generated by Django 2.1.7 on 2019-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191107_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tag_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
