# Generated by Django 2.1.7 on 2019-11-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_events_tag_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerSlot',
            fields=[
                ('timerId', models.AutoField(primary_key=True, serialize=False)),
                ('weeklystring', models.CharField(max_length=45)),
                ('weekly_value', models.IntegerField(blank=True, default=1, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=0)),
                ('timeinseconds', models.IntegerField(blank=True, default=1, null=True)),
                ('machine_id', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.DO_NOTHING, to='users.MachineDetails')),
            ],
        ),
    ]
