#!/bin/bash

NAME="brilliantPet"                                 # Name of the application
DJANGODIR=/home/karan/Documents/venvs/brilliantPet/brilliantPet            # Django project directory
SOCKFILE=0.0.0.0:8000    # we will communicte using this unix socket
USER=karan                                       # the user to run as
GROUP=sudo                                    # the group to run as
NUM_WORKERS=3                                 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=brilliantPet.settings            # which settings file should Django use
DJANGO_WSGI_MODULE=brilliantPet.wsgi                    # WSGI module name
threads=10

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
 --name $NAME \
 --workers $NUM_WORKERS \
 --user=$USER --group=$GROUP \
 --bind=$SOCKFILE \
 --log-level=debug \
 --threads=$threads\
 --log-file=-